apiVersion: v1
kind: Service
metadata:
  name: gerador-de-planilha
  namespace: gerador-de-planilha
  labels:
    app: gerador-de-planilha
    managed-by: backstage
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: gerador-de-planilha
